import React, { useState } from 'react';
import Button from '../../../components/ui/Button';
import Icon from '../../../components/AppIcon';

const ActionButtons = ({ 
  sensitivities, 
  deviceSpecs, 
  onSave, 
  onExport, 
  onGenerateQR,
  className = '' 
}) => {
  const [isSaving, setIsSaving] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [isGeneratingQR, setIsGeneratingQR] = useState(false);
  const [showSuccess, setShowSuccess] = useState('');

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const config = {
        id: Date.now(),
        name: `Config ${new Date()?.toLocaleDateString()}`,
        sensitivities,
        deviceSpecs,
        createdAt: new Date()?.toISOString()
      };
      
      const savedConfigs = JSON.parse(localStorage.getItem('sensitivity_configs') || '[]');
      savedConfigs?.push(config);
      localStorage.setItem('sensitivity_configs', JSON.stringify(savedConfigs));
      
      if (onSave) onSave(config);
      setShowSuccess('saved');
      setTimeout(() => setShowSuccess(''), 2000);
    } catch (error) {
      console.error('Error saving configuration:', error);
    } finally {
      setIsSaving(false);
    }
  };

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const exportData = {
        appName: 'VIZxSENSI',
        version: '1.0.0',
        exportDate: new Date()?.toISOString(),
        configuration: {
          sensitivities,
          deviceSpecs
        }
      };
      
      const dataStr = JSON.stringify(exportData, null, 2);
      const dataBlob = new Blob([dataStr], { type: 'application/json' });
      const url = URL.createObjectURL(dataBlob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = `freefire-sensitivity-${Date.now()}.json`;
      document.body?.appendChild(link);
      link?.click();
      document.body?.removeChild(link);
      URL.revokeObjectURL(url);
      
      if (onExport) onExport(exportData);
      setShowSuccess('exported');
      setTimeout(() => setShowSuccess(''), 2000);
    } catch (error) {
      console.error('Error exporting configuration:', error);
    } finally {
      setIsExporting(false);
    }
  };

  const handleGenerateQR = async () => {
    setIsGeneratingQR(true);
    try {
      const configData = {
        s: sensitivities,
        d: deviceSpecs,
        t: Date.now()
      };
      
      const encodedData = btoa(JSON.stringify(configData));
      const shareUrl = `${window.location?.origin}/sensitivity-calculator?import=${encodedData}`;
      
      // Create QR code data URL (mock implementation)
      const qrData = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shareUrl)}`;
      
      if (onGenerateQR) onGenerateQR({ url: shareUrl, qrCode: qrData });
      setShowSuccess('qr');
      setTimeout(() => setShowSuccess(''), 2000);
    } catch (error) {
      console.error('Error generating QR code:', error);
    } finally {
      setIsGeneratingQR(false);
    }
  };

  const copyToClipboard = async () => {
    const configText = `Free Fire Sensitivity Settings:\n\nGeneral: ${sensitivities?.general || 50}\nRed Dot: ${sensitivities?.redDot || 50}\n2x Scope: ${sensitivities?.scope2x || 50}\n4x Scope: ${sensitivities?.scope4x || 50}\n8x Scope: ${sensitivities?.scope8x || 50}\nFree Camera: ${sensitivities?.freeCamera || 50}\n\nDevice: ${deviceSpecs?.resolution} @ ${deviceSpecs?.fps}fps\nRAM: ${deviceSpecs?.ram?.toUpperCase()}\nDPI: ${deviceSpecs?.dpi}\n\nGenerated by VIZxSENSI Calculator`;
    
    try {
      await navigator.clipboard?.writeText(configText);
      setShowSuccess('copied');
      setTimeout(() => setShowSuccess(''), 2000);
    } catch (error) {
      console.error('Error copying to clipboard:', error);
    }
  };

  return (
    <div className={`space-y-4 ${className}`}>
      {/* Primary Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <Button
          variant="default"
          onClick={handleSave}
          loading={isSaving}
          iconName="Save"
          iconPosition="left"
          className="gaming-shadow-primary"
        >
          Save Configuration
        </Button>

        <Button
          variant="outline"
          onClick={handleExport}
          loading={isExporting}
          iconName="Download"
          iconPosition="left"
        >
          Export Settings
        </Button>
      </div>
      {/* Secondary Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <Button
          variant="secondary"
          onClick={handleGenerateQR}
          loading={isGeneratingQR}
          iconName="QrCode"
          iconPosition="left"
        >
          Generate QR Code
        </Button>

        <Button
          variant="ghost"
          onClick={copyToClipboard}
          iconName="Copy"
          iconPosition="left"
        >
          Copy Settings
        </Button>
      </div>
      {/* Success Messages */}
      {showSuccess && (
        <div className="flex items-center justify-center space-x-2 py-3 px-4 bg-success/10 text-success rounded-lg gaming-transition">
          <Icon name="CheckCircle" size={16} />
          <span className="text-sm font-medium">
            {showSuccess === 'saved' && 'Configuration saved successfully!'}
            {showSuccess === 'exported' && 'Settings exported successfully!'}
            {showSuccess === 'qr' && 'QR code generated successfully!'}
            {showSuccess === 'copied' && 'Settings copied to clipboard!'}
          </span>
        </div>
      )}
      {/* Quick Share */}
      <div className="pt-4 border-t gaming-border-subtle">
        <div className="flex items-center justify-between">
          <span className="text-sm text-muted-foreground">Quick Share:</span>
          <div className="flex items-center space-x-2">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => window.open('https://instagram.com/vizxsensi', '_blank')}
              className="hover:text-primary"
            >
              <Icon name="Instagram" size={16} />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => window.open('https://twitter.com/intent/tweet?text=Check out my Free Fire sensitivity settings!', '_blank')}
              className="hover:text-primary"
            >
              <Icon name="Twitter" size={16} />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => {
                if (navigator.share) {
                  navigator.share({
                    title: 'My Free Fire Sensitivity Settings',
                    text: 'Check out my optimized Free Fire sensitivity configuration!',
                    url: window.location?.href
                  });
                }
              }}
              className="hover:text-primary"
            >
              <Icon name="Share2" size={16} />
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ActionButtons;